### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by llfjahn** [bluemaex/homebridge-denon-quickselect#1]
I dont get it to work. What should I put in Host? The IP-Adress?
I get this Error:

`Error: Invalid URI "http:///goform/AppCommand.xml"
    at Request.init (/usr/local/lib/node_modules/homebridge-denon-quickselect/node_modules/request/request.js:274:31)
    at new Request (/usr/local/lib/node_modules/homebridge-denon-quickselect/node_modules/request/request.js:128:8)
    at request (/usr/local/lib/node_modules/homebridge-denon-quickselect/node_modules/request/index.js:54:10)
    at Function.post (/usr/local/lib/node_modules/homebridge-denon-quickselect/node_modules/request/index.js:62:12)
    at Promise (/usr/local/lib/node_modules/homebridge-denon-quickselect/index.js:37:13)
    at DenonQuickselect.doRequest (/usr/local/lib/node_modules/homebridge-denon-quickselect/index.js:36:10)
    at DenonQuickselect.getState (/usr/local/lib/node_modules/homebridge-denon-quickselect/index.js:58:8)
    at emitThree (events.js:116:13)
    at emit (events.js:194:7)
    at Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:120:10)`

**Comment by jlilja** [comment]
I've stumbled upon this as well. Did you find an answer to this?

Also relevant XKCD https://xkcd.com/979/

**Comment by jlilja** [comment]
Found it. 

Like the above asked, what should the host represent. Just type in the IP of the receiver and it'll work out fine.

**Comment by bluemaex** [comment]
@jlilja @MeinMilchKaffee Exactly you need to put the IP or the hostname of the receiver into the hosts field. 

I will add a point to the Readme to clarify this - Thanks! (and sorry for the late reply)
